project:
  type: default # website
  output-dir: _site
  preview:
    host: 0.0.0.0
    port: 6778
    browser: false
    watch-inputs: true

format:
  revealjs: 
    theme: [white, slides.scss]
    slide-number: true
    html-math-method:
      method: mathjax   
    default-image-extension: ""
    controls-layout: bottom-right
    controls-tutorial: true
    preview-links: auto
    reference-location: document
    footnotes-hover: true
    scrollable: true
    width: 1100
