services:
  build-quarto:
    init: true
    build:
      context: .
      dockerfile: Dockerfile
    hostname: build-quarto
    ports:
      - "6778:6778"
    container_name: build-quarto
    volumes:
      - ./slides-markdown/slides/:/data
    command: bash -c "bash utils/init.sh && chmod +x /data/publish.sh && /data/publish.sh"